WHITESPACE   = _{ " " | "\t" | NEWLINE }
NEWLINE      = _{ "\r\n" | "\n" }
COMMENT      = _{ LINE_COMMENT | HASH_COMMENT }
LINE_COMMENT = _{ "//" ~ (!NEWLINE ~ ANY)* }
HASH_COMMENT = _{ "#" ~ (!NEWLINE ~ ANY)* }

/// /
// Entry Points
/// /
file = { SOI ~ item* ~ EOI }
item = { metadata* ~ (density_decl | function_decl | using_stmt | expr_stmt) }

/// /
// Metadata / Attributes
/// /
metadata      = { "@" ~ ident ~ metadata_args? }
metadata_args = {
    "(" ~ (kv_pair_list | expr_list)? ~ ")"
}
kv_pair_list  = { kv_pair ~ ("," ~ kv_pair)* }
kv_pair       = { ident ~ "=" ~ expr }

/// /
// Using
/// /
using_stmt = { "using" ~ ident_path ~ ";"? }

/// /
// Density Declarations
/// /
density_decl = {
    "density" ~ function_decl
}

generic_args = { "<" ~ gerericparam ~ ("," ~ gerericparam)* ~ ">" }

/// /
// Function Declaration
/// /
function_decl = {
    "function" ~ ident ~ generic_args? ~ param_list_wrap? ~ function_definition
}

param_list_wrap = { "(" ~ param_list? ~ ")" }
param_list      = { param ~ ("," ~ param)* }
param           = { ident ~ ident? }
gerericparam    = { ident ~ ident }

function_definition = {
    block
  | ("=" ~ expr)
}

/// /
// Block (GLSL-like)
/// /
block = {
    "{" ~ block_stmt* ~ "}"
}

block_stmt = {
    ("let" ~ ident ~ "=" ~ expr ~ ";")
  | ("return" ~ expr ~ ";")
  | expr_stmt
}

expr_stmt = { expr ~ ";" }

/// /
// Expressions
/// /
expr = _{ infix_expr }

infix_expr = { add_expr }
add_expr   = { mul_expr ~ (plus_op ~ mul_expr)* }
mul_expr   = { unary_expr ~ (mul_op ~ unary_expr)* }

plus_op = { "+" }
mul_op  = { "*" }

unary_expr = {
    primary_expr
  | (("-" | "!") ~ unary_expr)
}

primary_expr = {
    literal
  | function_call
  | "(" ~ expr ~ ")"
}

/// /
// Function Call
/// /
function_call = {
    ident_path ~ generic_args? ~ arg_list?
}

arg_list = {
    immediate_arg_list
  | named_arg_list
}

immediate_arg_list = { "(" ~ expr_list? ~ ")" }

named_arg_list = { "(" ~ named_arg ~ ("," ~ named_arg)* ~ ","? ~ ")" }
named_arg      = { ident ~ ":" ~ expr }

// arg_list = { expr ~ ("," ~ expr)* }

/// /
// Constructor-like Blocks
/// /
// constructor_call = {
// ident ~ generic_args? ~ "{" ~ kv_pair_list? ~ "}"
// }

/// /
// Identifiers and Paths
/// /
ident = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }

ident_path = @{ ident ~ (("/" | ":") ~ ident)* }

/// /
// Literals
/// /
literal = _{ number | string | array }

number =  { float | int }
float  = @{ ASCII_DIGIT+ ~ "." ~ ASCII_DIGIT+ }
int    = @{ ASCII_DIGIT+ }

string = @{ "\"" ~ (!"\"" ~ ANY)* ~ "\"" }

array     = { "[" ~ expr_list? ~ "]" }
expr_list = { expr ~ ("," ~ expr)* }
