use crate::{spmt::model::PermutationTableInput, transform_rcl::sanitize_name};

/// Derives the Rust buffer/variable name for a permutation table.
/// This matches the naming convention used in the WGSL shaders generated by
/// `transform_naga`.
pub fn perm_table_var_name(perm_table: &PermutationTableInput) -> String {
    sanitize_name(&format!(
        "perm_table_{}_{}_{}",
        perm_table.ident,
        perm_table.subident_index,
        perm_table.subident.as_ref().unwrap_or(&"".to_string())
    ))
}

/// Derives the field name on the `PermutationTables` struct for a permutation
/// table. This matches the naming convention used by the RCL `orchestration.rs`
/// codegen (i.e. `transform_orchestration_rcl`).
pub fn perm_table_field_name(perm_table: &PermutationTableInput) -> String {
    sanitize_name(&format!(
        "{}_{}_{}",
        perm_table.ident,
        perm_table.subident_index,
        perm_table.subident.as_ref().unwrap_or(&"".to_string())
    ))
}

/// Derives the CUDA C++ member/parameter name for a permutation table.
/// Matches the naming used by `transform_cuda::types::permutation_table_param_name`.
pub fn perm_table_cuda_param_name(perm_table: &PermutationTableInput) -> String {
    sanitize_name(&format!(
        "perm_table_{}_{}_{}",
        perm_table.ident,
        perm_table.subident_index,
        perm_table.subident.as_deref().unwrap_or("")
    ))
}
