use crate::{spmt::model::PermutationTableInput, transform_rcl::sanitize_name};

/// Derives the Rust buffer/variable name for a permutation table.
/// This matches the naming convention used in the WGSL shaders generated by
/// `transform_naga`.
pub fn perm_table_var_name(perm_table: &PermutationTableInput) -> String {
    match perm_table {
        PermutationTableInput::PerlinNoise {
            ident,
            subident,
            subident_index,
        } => sanitize_name(&format!(
            "perm_table_{}_{}_{}",
            ident,
            subident_index,
            subident.as_ref().unwrap_or(&"".to_string())
        )),
        PermutationTableInput::Base3DNoise => "base3d_perm_table".to_string(),
    }
}

/// Derives the field name on the `PermutationTables` struct for a permutation
/// table. This matches the naming convention used by the RCL `orchestration.rs`
/// codegen (i.e. `transform_orchestration_rcl`).
pub fn perm_table_field_name(perm_table: &PermutationTableInput) -> String {
    match perm_table {
        PermutationTableInput::PerlinNoise {
            ident,
            subident,
            subident_index,
        } => sanitize_name(&format!(
            "{}_{}_{}",
            ident,
            subident_index,
            subident.as_ref().unwrap_or(&"".to_string())
        )),
        PermutationTableInput::Base3DNoise => "base3d_perm_table".to_string(),
    }
}
